### ISSUE TITLE
error in pimatic when posting from android app

### ISSUE THREAD

**Issue by sebastienvg** [Oitzu/pimatic-location#11]
I having this error after I restarted pimatic with latest dev version of plugin and app

```
19:34:04.474 [pimatic] error: A uncaught exception occured: TypeError: Cannot read property 'legs' of undefined
19:34:04.474 [pimatic] error:>    at LocationDevice.updateLocationCB (/pimatic-location.coffee:85:44)
19:34:04.474 [pimatic] error:>    at IncomingMessage.<anonymous> (/usr/local/node_modules/googlemapsutil/lib/httputil.js:40:16)
19:34:04.474 [pimatic] error:>    at IncomingMessage.EventEmitter.emit (events.js:117:20)
19:34:04.474 [pimatic] error:>    at _stream_readable.js:920:16
19:34:04.474 [pimatic] error:>    at process._tickCallback (node.js:415:13)
19:34:04.474 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
19:34:04.494 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
```

and this is how line 85 of pimatic-location/pimatic-location.coffee looks like 

`route_distance = data['routes'][0]['legs'][0]['distance']['value']`

**Comment by Oitzu** [comment]
How often does this error happen? Everytime you update your location by phone or just now and then? Looks like the google maps api doesn't gave back a route for your current position.

**Comment by Oitzu** [comment]
Published Version 0.0.7 of the plugin which catches the error and gives debug output about the cause.

**Comment by sebastienvg** [comment]
well the new plugin resolved the issue, I just messaged my wife to turn on pimatic-location on her phone and save/test, I'll keep you in the loop.

**Comment by Oitzu** [comment]
Well, as far as i know the gmaps-api has a limited number of calls you can make per day. Maybe you exceeded this?
The error/debug-output should show more info if this happens again.

**Comment by sebastienvg** [comment]
I remember I've read about that too (the limited numbers of call) however I believe one is able to provide API key or token to bypass the restriction of call without the API key. I'll see if I can find this link again. That's would be great if we could have the option in the plugin for the API key?!

**Comment by Oitzu** [comment]
See: #12
