### ISSUE TITLE
Delete fork dependency of the pimatic-plugin to the plugin-template

### ISSUE THREAD

**Issue by sweetpi** [Oitzu/pimatic-location#17]
The problem is that I can't fork the pimatic-plugin repository because it is a fork of my plugin-template. Could you "detach" the repo? 

http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by Oitzu** [comment]
i contacted the github support about this issue.

**Comment by Oitzu** [comment]
Fork is detached from the original.
