### ISSUE TITLE
App close upon saving

### ISSUE THREAD

**Issue by sebastienvg** [Oitzu/pimatic-location#3]
I tried to set this up on a stock GalaxyS3 with KittKatt and the app crash each time I try to save the settings, port 444 https (just like my nexus5 lollipop) that was running dev branch but then I updated to master and still works without issue.

**Comment by Oitzu** [comment]
Are you saying it's running fine on master but fails to start on the dev Version?
That would be strange, as both Versions should be the identical 1.0.1 at the moment.

**Comment by sebastienvg** [comment]
Both my devices run master branch version, Nexus has no issue GalaxyS3 crash upon saving. Also I noticed a huge battery drain, I am trying to play around with the refresh see if I can improve this. Right now pimatic-location uses even more power than display :(

**Comment by Oitzu** [comment]
I will try it on my lenovo tablet that runs kitkat.
S4 with jellybean runs fine.
Does the battery drain happens on both devices? Try to deactivate GPS if not needed.

**Comment by Oitzu** [comment]
Runs fine on my lenovo tablet. Do you have any possibilty to see in logcat the reason of the crash?

**Comment by sebastienvg** [comment]
I'll have to wait later today to check on the S3 (it's my daughter device). I didn't check battery drain on the s3. I'll keep GPS on as I need it most of the time. I'll get back with more details.

**Comment by Oitzu** [comment]
About the battery drain see #4.

**Comment by Oitzu** [comment]
Is this still a thing? Or does it work on the galaxy s3 now?

**Comment by sebastienvg** [comment]
seems to be resolved, sorry I didn't report earlier

**Comment by Oitzu** [comment]
Okay. No problem. Thx for the reply.
