### ISSUE TITLE
Android 5 not supported? [LG G3]

### ISSUE THREAD

**Issue by georg90** [Oitzu/pimatic-location#31]
Hi!

I recently got a LG G3 and I get the error: "Parsing error" when I try to install the apk.
As google says some apps might not be compatible with the Ultra HD resolution of the G3.

Can you have a look into it? Any information I can provide?

**Comment by Oitzu** [comment]
Hi!
Thank you for your report. As i don't have any Android 5 Devices it isn't tested on Android 5 by myself, yet. I don't think its a problem with the Ultra HD resolution of the G3.
The currently targetSdkVersion of the app is Android 19 (Android 4.4). i will lift the targetSdkVersion to 21 (Android 5.0) and look what happens. 
Maybe there is some sort of not backward compatible code in there.

**Comment by georg90** [comment]
sounds good! Thanks! 
If you lifted the sdk - I'll test asap

**Comment by georg90** [comment]
I "developed" a simple app for my phone (see: https://github.com/pimatic/pimatic/issues/651)
I got the same error - until I lifted the target sdk to 22 (min to 17) and `@app_name` wasn't equal to the name in the manifest..

**Comment by Oitzu** [comment]
Uploaded a new apk. Could you test this?

**Comment by georg90** [comment]
Same error - I'll try different methods at home. Can you upload it to a cloud platform? Maybe within is wrong ?!

**Comment by Oitzu** [comment]
Runs on my Android 5.0.1 Test-Device. As you seem to have Android Studio installed, maybe you can clone the repo and run it with the debugger?
Here is a link to dropbox with the apk:
https://www.dropbox.com/s/1ioeqxyrwhcu0pm/pimatic-location.apk?dl=0

**Comment by georg90** [comment]
@Oitzu This works! Thanks a lot!

I guess github is causing error?

**Comment by Oitzu** [comment]
Great. Maybe it cached the download or something like that? Other users hadn't any problems with the github download. But I think I will soon open the project for donations to register a Google  play store account and upload the app to the playstore. A few people already said they would donate a few euros/dollars for that issue.
