### ISSUE TITLE
Didn't received correct Gmaps-Api response!

### ISSUE THREAD

**Issue by p4co86** [Oitzu/pimatic-location#35]
Since today i get this error, but i use icloud and dont use any apikey

error [pimatic-location]: Didn't received correct Gmaps-Api response!

**Comment by Oitzu** [comment]
Wow.. didn't saw that. Is this still a thing, or solved?
The gmaps-api is used regardless if android or iphone is used, it is used to calculate distances.

**Comment by p4co86** [comment]
i have set intervall from 60000 to 300000 now its pops up just sometime

**Comment by Oitzu** [comment]
Well... in this case i guess this was an "to many requests to gmaps api" Problem.
If you need an higher intervall, get an API-Key from google.

**Comment by n3roGit** [comment]
I have the same issue! After adding Api Key and restaring pimnatic its still not working
