### ISSUE TITLE
Trouble with apple login

### ISSUE THREAD

**Issue by PiNow** [Oitzu/pimatic-location#36]
Hi, I am trying to use the location app for my iphone, but got trapped in the two factor verification procedure. Every time pimatic tries to login to my account, I get a message on my phone, providing me with a code I obviously can't enter on the pi at that moment. Alternatively, I try to use an app specific password. This does solve the problem of getting messages on my iphone, but does not solve the problem of getting access. Instead, I get this kind of messages in the Pimatic app:
warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
error [pimatic]: A uncaught exception occured: Error: connect ECONNREFUSED at errnoException (net.js:901:11) at Object.afterConnect [as oncomplete](net.js:892:19) This is most probably a bug in pimatic or in a module, please report it!

Any suggestions, except for the obvious: stop using the two factor verification?

**Comment by Oitzu** [comment]
I think we are out of luck on this one.
The underlying npm module: "https://www.npmjs.com/package/iphone-finder" doesn't support it and i can't find any npm module that would support the two factor auth.

**Comment by PiNow** [comment]
Hi Oitzu, thank you for your reply. A couple of weeks after leaving this comment, the problem solved itself. Suddenly, I was not asked for the verification anymore and it has been like that since. As far as I am aware of, I have not changed any of the settings....

**Comment by Oitzu** [comment]
funny. :D Well i have no iDevices to test this myself.. so closed.
