### ISSUE TITLE
App on nexus 6p

### ISSUE THREAD

**Issue by jochem4207** [Oitzu/pimatic-location#37]
I cannot install the app on nexus 6p it simply gives  a "can't open" message when I click on the apk that i've put on my phone in the downloads folder. I did check the box that non-store apps can be installed.

**Comment by jochem4207** [comment]
Closed: Used this app to isntall https://play.google.com/store/apps/details?id=com.IQBS.android.appInstaller&hl=en

**Comment by Oitzu** [comment]
I wonder what was the cause...? Which Android Version is the nexus 6p?
